# Change these first
owner: Downly-Net # Your GitHub organization or username, where this repository lives
repo: YMOZ # The name of this repository

sites:
  - name: Main site
    url: https://ymoz.com
  - name: IMAP
    url: https://$IMAPSERVER
  - name: POP
    url: https://$IMAPSERVER  
  - name: SOGo
    url: https://mail.ymoz.com/SOGo
  - name: Email admin
    url: https://$IMAPSERVER
  - name: CalDav
    method: POST
    url: https://$IMAPSERVER/SOGo/dav/ 
    expectedStatusCodes:
      - 200
      - 201
      - 401
      - 404
  - name: CardDav
    method: POST
    url: https://$IMAPSERVER/SOGo/dav/ 
    expectedStatusCodes:
      - 200
      - 201
      - 401
      - 404   
   

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ymoz.com
  # baseUrl: /your-repo-name
  logoUrl: https://ymoz.com/assets/img/logo-light.svg
  name: Network Status
  introTitle: "Uptime monitor and status page for **YMOZ** powered by **Downly**."
  introMessage: This **real-time** status page collects data for YMOZ services.
  navbar:
    - title: Home
      href: https://ymoz.com
      
  status-website:
  theme: dark    
  favicon: https://ymoz.com/assets/favicon/favicon.ico
  faviconSvg: https://ymoz.com/assets/favicon/safari-pinned-tab.svg
  
  i18n:
  footer: Network Status monitered by [Downly](https://downly.net)
    
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
      
  commitMessages:
  commitAuthorName: "Downly Bot"
  commitAuthorEmail: "bot@downly.net"    
      
user-agent: Downly-Net
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
